language: node_js
node_js:
- 'stable'
matrix:
  fast_finish: true
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g grunt-cli bower
- bower install
script:
- grunt build
deploy:
  provider: npm
  email: simon@simonemms.com
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/ui-router.login
